apiVersion: v1
kind: Service
metadata:
  name: hbms-service
spec:
  type: NodePort
  selector:
    app: hbms
  ports:
    - nodePort: 30000
      port: 8080
      targetPort: 80 # This directs traffic to the local pods in the cluster
