apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hbms-stack
  region: us-east-2

vpc:
  id: vpc-03504f8251682bfbd
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0e18e832a5b5eec19
      my-new-stack-PublicSubnet02:
        id: subnet-0dca962d8c2fbfe80
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-04c4cbda28d2bf254
      my-new-stack-PrivateSubnet02:
        id: subnet-0b064c250a3dc9764

nodeGroups:
  - name: hbms-public-workers
    instanceType: t3.micro
    desiredCapacity: 2
  - name: hbms-private-workers
    instanceType: t3.micro
    desiredCapacity: 1
    privateNetworking: true