# Generated by Django 3.2.5 on 2023-08-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_patienbookings_pb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bedtype1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedtype2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedtype3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
